"""Publicly verifiable secret sharing (Schoenmakers, CRYPTO 1999).

Implements B. Schoenmakers, "A Simple Publicly Verifiable Secret Sharing
Scheme and its Application to Electronic Voting", CRYPTO 1999, LNCS 1666,
pp. 148-164: a (t+1)-out-of-n Shamir sharing of a secret S in the exponent,
with every share individually ElGamal-encrypted under the recipient's public
key and a single non-interactive (Fiat-Shamir) Schnorr proof that the whole
transcript is consistent.  Any third party -- not just the recipients -- can
verify the dealer's distribution on the public transcript alone.

Precursors: M. Stadler, "Publicly Verifiable Secret Sharing", EUROCRYPT 1996
(double-discrete-log PVSS), and E. Fujisaki, T. Okamoto, "A practical and
provably secure scheme for publicly verifiable secret sharing", ASIACRYPT
1998.  Schoenmakers replaces their expensive double-DL proofs with a single
ElGamal/DH proof of consistency, reducing the security assumption to DDH.

Structure of a transcript (all group elements live in the order-q subgroup
generated by g mod p):

    secret_exponent : C_0 = g^S (the secret, committed in the exponent)
    commitments     : [C_j = g^a_j] for j = 0..t (C_0 = g^S, f = S + a_1 x + ...)
    ciphertexts     : [(W_i, V_i)] for i = 1..n, W_i = g^r_i, V_i = Y_i * y_i^r_i
                      with Y_i = g^f(i) and y_i = g^sk_i the recipient's key
    proof           : Fiat-Shamir Schnorr proof (challenge c = H(transcript)):
                      z_j   = u_j + c*a_j mod q   (proof of knowledge of a_j)
                      z_i   = w_i + c*r_i mod q   (proof that V_i encrypts Y_i)
                      B_j   = [g^u_j]
                      B_i   = [(g^w_i, y_i^w_i)]  (both components are public,
                      matching the paper's B_i' and B_i'')
    n, threshold, recipient_pks : instance data bound into the challenge

Verification (Section 3 of the paper), for all j and i, with Y_i computed by
the verifier as prod_j C_j^(i^j):

    g^z_j  = B_j  * C_j^c
    g^z_i  = B_i' * W_i^c            where B_i'  = g^w_i
    y_i^z_i = B_i'' * (V_i / Y_i)^c  where B_i'' = y_i^w_i

Reconstruction is public: recipient i decrypts Y_i = V_i / W_i^sk_i and
publishes it; anyone combines any t+1 of the Y_i by Lagrange interpolation in
the exponent, yielding Y = g^S.  Recovering the field element S itself is a
discrete log; for small secrets this is done by baby-step giant-step pullback
(Section 4 of the paper, election-ballot style).
"""

import hashlib
import math
import secrets

from .core import field_for, lagrange_coefficient
from .gf import GF, default_field

_DOMAIN_SEP = b"sssx pvss v1"


def _group_width(field):
    return (field.p.bit_length() + 7) // 8


def _encode_public_parts(field, n, threshold, commitments, ciphertexts, pks):
    """Deterministic byte encoding of the public transcript, for the FS hash."""
    w = _group_width(field)
    parts = [_DOMAIN_SEP]
    parts.append(n.to_bytes(4, "big"))
    parts.append(threshold.to_bytes(4, "big"))
    for c in commitments:
        parts.append(c.to_bytes(w, "big"))
    for wi, vi in ciphertexts:
        parts.append(wi.to_bytes(w, "big"))
        parts.append(vi.to_bytes(w, "big"))
    for y in pks:
        parts.append(y.to_bytes(w, "big"))
    return b"".join(parts)


def _challenge(field, n, threshold, commitments, ciphertexts, pks):
    data = _encode_public_parts(field, n, threshold, commitments, ciphertexts, pks)
    return int.from_bytes(hashlib.sha256(data).digest(), "big") % field.q


def _poly_eval_mod_q(coeffs, x, q):
    """Horner evaluation of coeffs mod q (shares are exponents in Z_q)."""
    acc = 0
    for a in reversed(coeffs):
        acc = (acc * x + a) % q
    return acc


def _rand_nonzero(rand, q):
    """Draw a nonzero exponent in [1, q-1] (g^0 = 1 is not a subgroup element)."""
    while True:
        r = rand(q)
        if r != 0:
            return r


def pvss_keygen(field=None):
    """Generate a PVSS recipient key pair (sk, pk) with pk = g^sk in Z_q^*. (Schoenmakers CRYPTO 1999, Section 2.)"""
    field = field_for(field)
    if field.g is None or field.q is None:
        raise ValueError("field needs a prime-order subgroup (g, q)")
    sk = 1 + secrets.randbelow(field.q - 1)
    return sk, field.commit(sk)


def pvss_deal(secret, threshold, recipient_pks, field=None, randfunc=None):
    """Deal a (threshold+1)-out-of-len(pks) PVSS sharing of `secret` in the exponent.

    Returns the public transcript dict (see module docstring).  Every
    recipient public key must be a valid element of the order-q subgroup;
    ValueError is raised otherwise.  `secret` is reduced mod q and must not
    reduce to 0 (g^0 = 1 is not a subgroup element).  The ElGamal
    randomness r_i is drawn fresh per recipient; the Fiat-Shamir challenge is
    c = SHA-256("sssx pvss v1" || n || threshold || commitments || ciphertexts
    || recipient_pks) mod q.
    """
    field = field_for(field)
    if field.g is None or field.q is None:
        raise ValueError("field needs a prime-order subgroup (g, q)")
    n = len(recipient_pks)
    if not (1 <= threshold < n):
        raise ValueError("require 1 <= threshold < n")
    pks = [field.element(y) for y in recipient_pks]
    for y in pks:
        field._check_subgroup(y)
    rand = randfunc or secrets.randbelow
    q = field.q
    secret = secret % q
    if secret == 0:
        raise ValueError("secret reduces to 0 mod q")

    poly = [secret] + [_rand_nonzero(rand, q) for _ in range(threshold)]
    commitments = [field.commit(a) for a in poly]
    ciphertexts = []
    r_i = []
    for i in range(1, n + 1):
        fi = _poly_eval_mod_q(poly, i, q)
        yi = field.commit(fi)
        ri = _rand_nonzero(rand, q)
        r_i.append(ri)
        wi = field.commit(ri)
        vi = field.mul(yi, field.pow(pks[i - 1], ri))
        ciphertexts.append((wi, vi))

    u_j = [_rand_nonzero(rand, q) for _ in range(threshold + 1)]
    w_i = [_rand_nonzero(rand, q) for _ in range(n)]
    b_j = [field.commit(u) for u in u_j]
    b_i = [(field.commit(w), field.pow(pks[i], w)) for i, w in enumerate(w_i)]
    c = _challenge(field, n, threshold, commitments, ciphertexts, pks)
    z_j = [(u + c * a) % q for u, a in zip(u_j, poly)]
    z_i = [(w + c * r) % q for w, r in zip(w_i, r_i)]

    return {
        "secret_exponent": commitments[0],
        "commitments": commitments,
        "ciphertexts": ciphertexts,
        "proof": {
            "challenge": c,
            "z_j": z_j,
            "z_i": z_i,
            "B_j": b_j,
            "B_i": b_i,
        },
        "n": n,
        "threshold": threshold,
        "recipient_pks": pks,
    }


def pvss_verify(transcript, field=None):
    """Verify a PVSS transcript fully publicly; returns bool, never raises.

    Checks subgroup membership of every public group element (commitments,
    ciphertexts, recipient keys, proof bases, and the stored secret
    exponent), consistency of the stored challenge with the recomputed
    Fiat-Shamir hash, and the three Schnorr verification equations of
    Schoenmakers CRYPTO 1999, Section 3.  Returns False for any malformed,
    out-of-subgroup, or inconsistent transcript.
    """
    field = field_for(field)
    if field.g is None or field.q is None:
        return False
    try:
        n = transcript["n"]
        threshold = transcript["threshold"]
        commitments = transcript["commitments"]
        ciphertexts = transcript["ciphertexts"]
        pks = transcript["recipient_pks"]
        proof = transcript["proof"]
        if len(commitments) != threshold + 1 or len(ciphertexts) != n:
            return False
        if len(pks) != n or not (1 <= threshold < n):
            return False
        z_j = proof["z_j"]
        z_i = proof["z_i"]
        b_j = proof["B_j"]
        b_i = proof["B_i"]
        if len(z_j) != threshold + 1 or len(z_i) != n:
            return False
        if len(b_j) != threshold + 1 or len(b_i) != n:
            return False

        public = list(commitments) + [transcript["secret_exponent"]]
        for wi, vi in ciphertexts:
            public.extend((wi, vi))
        public.extend(pks)
        public.extend(b_j)
        for b1, b2 in b_i:
            public.extend((b1, b2))
        for x in public:
            field._check_subgroup(x)

        if transcript["secret_exponent"] != commitments[0]:
            return False
        c = _challenge(field, n, threshold, commitments, ciphertexts, pks)
        if proof["challenge"] != c:
            return False

        g = field.g
        for j in range(threshold + 1):
            if field.pow(g, z_j[j]) != field.mul(b_j[j], field.pow(commitments[j], c)):
                return False
        for i in range(n):
            wi, vi = ciphertexts[i]
            b1, b2 = b_i[i]
            yi = field.eval_commit(commitments, i + 1)
            if field.pow(g, z_i[i]) != field.mul(b1, field.pow(wi, c)):
                return False
            lhs = field.pow(pks[i], z_i[i])
            rhs = field.mul(b2, field.pow(field.mul(vi, field.inv(yi)), c))
            if lhs != rhs:
                return False
        return True
    except (ValueError, TypeError, KeyError, IndexError):
        return False


def pvss_decrypt_share(transcript, sk, i, field=None):
    """Recipient decrypts its share Y_i = g^f(i) from the transcript.

    i is the 1-based share index (i-th recipient in the transcript's
    recipient list).  Raises ValueError on out-of-range index or malformed
    ciphertext elements.
    """
    field = field_for(field)
    n = transcript["n"]
    if not (1 <= i <= n):
        raise ValueError("share index out of range")
    wi, vi = transcript["ciphertexts"][i - 1]
    field._check_subgroup(wi)
    field._check_subgroup(vi)
    return field.mul(vi, field.inv(field.pow(wi, sk)))


def pvss_combine_exponent(Ys, indices, threshold, field=None):
    """Public reconstruction in the exponent: Y = prod_i Y_i^lambda_i = g^S.

    Ys are the decrypted g^f(i) values of the recipients at the 1-based share
    indices `indices`; lambda_i are the Lagrange coefficients at 0 over those
    indices.  The coefficients are computed over Z_q -- via
    core.lagrange_coefficient on a GF(q) wrapper, since the interpolation
    happens in the exponent ring, not in GF(p).  Requires at least
    threshold+1 shares; raises ValueError on inconsistent input sizes or
    out-of-subgroup Y_i.
    """
    field = field_for(field)
    if len(Ys) != len(indices):
        raise ValueError("Ys and indices must have equal length")
    if len(Ys) < threshold + 1:
        raise ValueError("need at least threshold+1 shares")
    for y in Ys:
        field._check_subgroup(y)
    lambdas = lagrange_coefficient(list(indices), 0, GF(field.q))
    y = 1
    for yi, lam in zip(Ys, lambdas):
        y = field.mul(y, field.pow(yi, lam))
    return y


def pvss_recover_small_secret(Y, bound, field=None):
    """Pull S back from Y = g^S by baby-step giant-step (Schoenmakers CRYPTO 1999, Section 4).

    Only feasible for small secrets: returns S as an int with 0 <= S < bound,
    or None if no such S is found.
    """
    field = field_for(field)
    field._check_subgroup(Y)
    g = field.g
    q = field.q
    m = max(1, math.isqrt(bound - 1) + 1) if bound >= 1 else 0
    if m == 0:
        return None
    baby = {}
    cur = 1
    for j in range(m):
        if cur not in baby:
            baby[cur] = j
        cur = field.mul(cur, g)
    ginv_m = field.pow(g, (-m) % q)
    cur = Y
    for k in range(m + 1):
        hit = baby.get(cur)
        if hit is not None:
            s = hit + k * m
            if s < bound:
                return s
        cur = field.mul(cur, ginv_m)
    return None
