[package]
name = "gp-crypto-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
gp-crypto = { path = ".." }

[[bin]]
name = "merkle"
path = "fuzz_targets/merkle.rs"
test = false
doc = false
bench = false

[[bin]]
name = "verify"
path = "fuzz_targets/verify.rs"
test = false
doc = false
bench = false

[[bin]]
name = "recover"
path = "fuzz_targets/recover.rs"
test = false
doc = false
bench = false

[workspace]
